{
	"name":"test",
	"version":"1.2.4",
	"upDateUrl":"http://download.dcloud.net.cn/HBuilder.9.0.2.windows.zip",
	"byte":230675187,
	"manifest":{
		"file":["index.js"],
		"del":["./del.js"],
		"detail":["新增项目编辑功能"]
	}
}
